### ISSUE TITLE
Zad 9 / Ćw 9 

### ISSUE THREAD

**Issue by MrD4rkne** [witek-formanski/WDP#40]
Chyba jest to mały bug.
Dla przykładu: 

```
 8 8
1 1 1 1 0 0 0 0
1 0 1 0 0 0 1 0
1 1 1 1 1 1 1 1
0 1 1 0 0 0 0 1
1 0 1 0 1 1 0 1
0 1 1 0 0 0 0 1
1 0 1 1 1 1 1 1
0 1 0 1 0 1 0 0
```

Wynik powinien być 2, a daje 3. Gdy dodajemy punkt do kolejki, to gdy jest on wodą, a jego poprzednik wyspą, to nie powinien się zwiększać stopień.

Czyli zamiast
```
            if (adj[y][x] == adj[u[1]][u[2]])
                dq.push_front({u[0], y, x});
            else
                dq.push_back({u[0] + 1, y, x});
```

powinno być(?):
```
// if land, then degree should be increased
            int level = adj[y][x] ? 1 : 0;
            if (adj[y][x] == adj[u[1]][u[2]])
                dq.push_front({u[0], y, x});
            else
                dq.push_back({u[0] + level, y, x});
 ```
@asajb

**Comment by asajb** [comment]
@MrD4rkne Kubica odwalił syf i dał inną treść zadania na OI i na tych ćwiczeniach. Na olimpiadzie skakanie między 0-1, 1-0 daje pkt.
Możesz to zmienić bez problemu.

**Comment by MrD4rkne** [comment]
A dobra, myślałem że po prostu bug, to wrzucę swoje działające, ale cały algorytm jest od Ciebie
